security:
    enable_authenticator_manager: true
    password_hashers:
         App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email  # Or use 'email' if you login with email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            provider: app_user_provider  
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password_hash
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/api/editor, roles: ROLE_EDITOR }
        - { path: ^/api/checker, roles: ROLE_CHECKER }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
