

services:
  backend:
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    container_name: whimsical_backend
    volumes:
      - ./whimsical-website-backend:/var/www/html
    depends_on:
      - db
    networks:
      - whimsical_net
    environment:
      DATABASE_URL: "mysql://symfony:symfony@db:3306/whimsical"

  db:
    image: mysql:8.0
    container_name: whimsical_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: whimsical
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - whimsical_mysql_data:/var/lib/mysql
    networks:
      - whimsical_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: whimsical_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: symfony
      PMA_PASSWORD: symfony
    depends_on:
      - db
    networks:
      - whimsical_net

networks:
  whimsical_net:

volumes:
  whimsical_mysql_data:
